#!/usr/bin/python3
"""
Define module for plc
"""
from models.base_model import BaseModel


class Plc(BaseModel):
    """
    place instance
    """

    city_id = ""
    user_id = ""
    name = ""
    description = ""
    rooms_number = 0
    bath_rooms = 0
    max_guest = 0
    a_night_price = 0
    latitude = 0.0
    long_tude = 0.0
    ame_ids = []

